os-852 add explanation for exit

diff --git a/files/check_instance_boot b/files/check_instance_boot
--- a/files/check_instance_boot
+++ b/files/check_instance_boot
@@ -46,6 +46,8 @@ if spawn_vm "${lockdir}/template.yaml" check_instance_boot_$HOSTNAME; then
   show_physical_host_of_vm
   # Check if VM can reach its gateway.
   check_network
+  exit $?
+  # do not clean up for now, keep the broken stack for debugging there
   retval=$?
   if ((retval)); then
     if ! cleanup_heat_stack; then
diff --git a/files/check_instance_snat b/files/check_instance_snat
--- a/files/check_instance_snat
+++ b/files/check_instance_snat
@@ -51,7 +51,8 @@ if spawn_vm "${lockdir}/template.yaml" check_instance_snat_$HOSTNAME; then
   show_physical_host_of_vm
   # Check if VM can reach its gateway.
   check_vm_pings
-  exit
+  exit $?
+  # do not clean up for now, keep the broken stack for debugging there
   retval=$?
   if ((retval)); then
     if ! cleanup_heat_stack; then
